[template]
keys        = [ "/skydns/local" ]
owner       = "nginx"
mode        = "0644"
src         = "nginx.stream.tmpl"
dest        = "/etc/nginx/conf.d/app.stream"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/usr/sbin/service nginx reload"
